title: Nilam Ghaware
url: "https://nilamGhaware.me"
baseurl: "."
author: Nilam Ghaware 
# description: "Prashik Patil's portfolio webpage"
markdown: kramdown
ins_logo: ""

tracking_id: #

footer: yes
footer_url: "https://github.com/"
footer_text: "With love"

sass:
    style: compressed
    sass_dir: _sass

# nav:
 # - name: "Photo Gallery"
 #   link: one.html
 # - name: "Resume"
 #   link: "/PrashikPatil_Resume .pdf"
 # - name: "Contact"
 #   link: "/contact.md"


theme: jekyll-theme-minimal
